load("@toolchains//:libs.bzl", "toolchain_libraries")
load(":defs.bzl", "haskell_toolchain_library")

python_bootstrap_binary(
    name = "generate_toolchain_libs",
    main = "generate_toolchain_libs.py",
)

[
    haskell_toolchain_library(
        name = lib,
        visibility = ["//..."],
    )
    for lib in toolchain_libraries
]
