load(":test_defs.bzl", "external_command_test")

haskell_binary(
    name = "test_bin",
    srcs = ["Spec.hs"],
    main = "Spec",
    link_style = "static",
    deps = [
        "//haskell:QuickCheck",
        "//haskell:base",
        "//haskell:hspec",
    ],
)

external_command_test(
    name = "my_haskell_test",
    cmd = ["$(exe_target :test_bin)"],
)
